version: '3.1'
services:
  backend:
    container_name: feast-orders-backend
    image: feast-orders-server
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - PROFILE=devpst
      - PST_URL=bear-db-container
      - PST_USERNAME=postgres
      - PST_PASSWORD=password
      - PST_DB=postgres
      - PST_PORT=5432
    networks:
      - feast-bear
  postgres:
    container_name: bear-db-container
    image: bear-db
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql:/var/lib/postgresql
    networks:
      - feast-bear
networks:
  feast-bear:
    driver: "bridge"