version: '3.1'
services:
  backend:
    container_name: feast-orders-backend
    image: feast-orders-server
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    container_name: bear-db-container
    image: bear-db
    build:
      context: ./
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"