version: '3.1'
services:
  backend:
    container_name: feast-orders-backend
    image: backend
    build: ./
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    container_name: feast-orders-database
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres