logging:
  level:
    root: INFO

spring:
  profiles: prod
  datasource:
    hikari:
      data-source-properties: stringtype=unspecified
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${PST_URL}:${PST_PORT}/${PST_DB}
    username: ${PST_USERNAME}
    password: ${PST_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
