logging:
  level:
    root: INFO

spring:
  spring:
    config:
      activate:
        on-profile: devpst
  datasource:
    hikari:
      data-source-properties: stringtype=unspecified
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${PST_URL:localhost}:${PST_PORT:5432}/${PST_DB:postgres}
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true