server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${PROFILE:prod}
  output:
    ansi:
      enabled: always
  banner:
    location: ./banner.txt
  main:
    allow-bean-definition-overriding: true

app:
  security:
    jwtSecret: feastBearSecretKey
    jwtExpirationMs: 86400000


application:
  title: Feast Bear Server
  version: 1.0.0