server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${PROFILE:prod}
  output:
    ansi:
      enabled: always
  banner:
    location: ./banner.txt
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false

application:
  title: Feast Bear Server
  version: 1.0.0
  security:
    jwtSecret: feastBearSecretKey
    jwtExpirationMs: 86400000
  task:
    errors:
      cron: 0 0 * * * *
      size: 500
      export: true
      path: ${HOME}/Desktop