server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: devpst
  output:
    ansi:
      enabled: always

app:
  security:
    jwtSecret: feastBearSecretKey
    jwtExpirationMs: 86400000