logging:
  level:
    root: WARN

spring:
  profiles: prod
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ${PSTURL}
    username: ${PSTUSERNAME}
    password: ${PSTPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
