name: Spring Boot Backend CI

on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  pull_request:
    branches: [ main ]
    paths: 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Maven Package
        run: mvn -X clean package
      - name: Maven Verify
        run: mvn clean verify
