name: FeastBear Orders Flutter CI

on:
  push:
    branches: [ main ]
    paths: 'mobile/orders**'
  pull_request:
    branches: [ main ]
    paths: 'mobile/orders**'

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./mobile/orders
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: stable
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
        
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
